version: "3.9"
services:
  app:
    build: ./docker/php
    container_name: loja-php-app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:1.25-alpine
    container_name: loja-php-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: loja-php-db
    environment:
      MYSQL_DATABASE: lojaphp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  composer:
    image: composer:2
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    entrypoint: ["composer"]
volumes:
  dbdata:
